### PR TITLE
remove default style, add core componenets with avios setup in utils …

### PR DESCRIPTION
**Pull request by kamiviolet**
…folder with 1st util function: getAllArticles, add basic styling for distinguishing components purpose only

### CODE REVIEW

**Review by EddTheDuck — CHANGES_REQUESTED** [review]
This is fine but please change the body text colour to something more readable, it is currently white with a white bg!

**Comment by kamiviolet** [comment]
hm? Edd, would it be the default setting of usersagent? its not on my side.. or should it add color: black to body in index.css just to be sure? Thanks! :)
image

**Review by EddTheDuck — APPROVED** [review]
Lovely, thanks Kami.

Feel free to merge :)

**Comment by kamiviolet** [comment]
thank you Edd!

**Pull request merged**
